
development:
  adapter: postgresql
  encoding: unicode
  database: groupup
  host: localhost
  username: admin
  password: admin
  pool: 5


production:
  adapter: postgresql
  encoding: unicode
  database: groupup
  pool: 15
